import Head from "next/head";
import Hero from "../Components/Hero";
import Jobs from "@/Components/Jobs";
import AboutUs from "@/Components/AboutUs";
import Reviews from "@/Components/Reviews";
import FAQ from "@/Components/FAQ";
import Contact from "@/Components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>CarmoDev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero />
      <Jobs />
      <AboutUs />
      <Reviews />
      <FAQ />
      <Contact />
    </>
  );
}
